baseURL = 'https://blog.aphonic.org'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'aphonic.org'
theme = "hugo-coder"

paginate = 20

pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[params]
  author = "Edwin Marshall"
  info = "Engineer | Blogger | Gamer"
  description = "The many ramblings of Edwin Marshall"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hideColorSchemeToggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/aspidites"

[[params.social]]
  name = "Resume"
  icon = "fa fa-file-text-o fa-2x"
  weight = 1
  url = "/resume.pdf"

[[menu.main]]
  name = "Blog"
  weight = 1
  url = "/posts"

